name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential cmake ninja-build gcc g++ gcc-12 g++-12
          sudo apt-get install -y libboost-graph-dev libboost-iostreams-dev libboost-filesystem-dev
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y nlohmann-json3-dev
          sudo apt-get install -y libisl-dev
          sudo apt-get install -y libpapi-dev papi-tools
          sudo apt-get install -y libzip-dev ziptool zipcmp zipmerge

          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"
          sudo add-apt-repository "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main"
          sudo apt-get update
          sudo apt-get install -y clang-format-19 clang-19 clang++-19 llvm-19

          pip install gcovr pytest

      - name: Build sdfglib
        run: |
          git config --global url."https://oauth2:${{ secrets.SDFGLIB_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git clone "https://oauth2:${{ secrets.SDFGLIB_TOKEN }}@github.com/daisytuner/sdfglib.git" /tmp/sdfglib
          cd /tmp/sdfglib
          git checkout abe57c08381461b6689cc215a9305e21c2b65642
          git submodule update --init --recursive --depth 1
          git lfs fetch

          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_BUILD_TYPE=Debug -DWITH_SYMENGINE_RCP=ON -DBUILD_TESTS:BOOL=OFF -DBUILD_BENCHMARKS:BOOL=OFF -DBUILD_BENCHMARKS_GOOGLE:BOOL=OFF  ..
          ninja -j$(nproc)
          sudo ninja install

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_BUILD_TYPE=Debug  ..
          ninja -j$(nproc)

          ./tests/sdfglib-einsum_test
